import type { IProduct } from './types'
import { ref } from 'vue'

export const products = ref<IProduct[]>([
  {
    id: 1,
    name: 'Lionel Messi',
    description: 'Napastnik, znany ze swojej precyzji i dryblingu.',
    price: 140,
    img: '/src/assets/leo.webp',
    legendary: true,
    position: 'Striker',
    attributes: {
      dribbling: 95,
      speed: 87,
      shot: 92,
      defensive: 69,
      overall: 95,
    },
  },
  {
    id: 5,
    name: 'Kylian Mbappé',
    description: 'Napastnik, z niebywałą szybkością i umiejętnościami technicznymi.',
    price: 125,
    img: '/src/assets/mbappe.webp',
    legendary: false,
    position: 'Striker',
    attributes: {
      dribbling: 91,
      speed: 96,
      shot: 85,
      defensive: 67,
      overall: 91,
    },
  },
  {
    id: 3,
    name: 'Neymar Jr',
    description: 'Napastnik, znany ze swoich zwodów i kreatywności na boisku.',
    price: 100,
    img: '/src/assets/neymar.webp',
    legendary: false,
    position: 'Striker',
    attributes: {
      dribbling: 94,
      speed: 92,
      shot: 88,
      defensive: 57,
      overall: 92,
    },
  },
  {
    id: 6,
    name: 'Mohamed Salah',
    description: 'Napastnik, o eksplozywnej szybkości i celnych strzałach.',
    price: 75,
    img: '/src/assets/salah.webp',
    legendary: false,
    position: 'Striker',
    attributes: {
      dribbling: 88,
      speed: 94,
      shot: 90,
      defensive: 70,
      overall: 89,
    },
  },
  {
    id: 4,
    name: 'Robert Lewandowski',
    description: 'Napastnik, uznawany za jednego z najlepszych strzelców na świecie.',
    price: 95,
    img: '/src/assets/lewandowski.webp',
    legendary: false,
    position: 'Striker',
    attributes: {
      dribbling: 84,
      speed: 81,
      shot: 95,
      defensive: 77,
      overall: 91,
    },
  },
  {
    id: 7,
    name: 'Harry Kane',
    description: 'Napastnik, znany z doskonałego wykończenia akcji i gry głową.',
    price: 90,
    img: '/src/assets/kane.webp',
    legendary: false,
    position: 'Striker',
    attributes: {
      dribbling: 83,
      speed: 76,
      shot: 93,
      defensive: 59,
      overall: 88,
    },
  },
  {
    id: 10,
    name: 'Manuel Neuer',
    description: 'Bramkarz, uznawany za jednego z najlepszych bramkarzy na świecie.',
    price: 105,
    img: '/src/assets/neuer.webp',
    legendary: false,
    position: 'Goalkeeper',
    attributes: {
      dribbling: 40,
      speed: 60,
      shot: 30,
      defensive: 97,
      overall: 92,
    },
  },
  {
    id: 2,
    name: 'Cristiano Ronaldo',
    description: 'Napastnik, znany ze swojej siły fizycznej i skuteczności w strzałach.',
    price: 130,
    img: '/src/assets/ronaldo.webp',
    legendary: true,
    position: 'Striker',
    attributes: {
      dribbling: 87,
      speed: 91,
      shot: 94,
      defensive: 68,
      overall: 93,
    },
  },
  {
    id: 8,
    name: 'Erling Haaland',
    description: 'Napastnik, mistrz gry w polu karnym z niesamowitą szybkością oraz strzałem',
    price: 135,
    img: '/src/assets/haaland.webp',
    legendary: false,
    position: 'Striker',
    attributes: {
      dribbling: 85,
      speed: 93,
      shot: 92,
      defensive: 62,
      overall: 90,
    },
  },
  {
    id: 9,
    name: 'Luka Modrić',
    description: 'Pomocnik, mistrz taktyki i precyzji w podaniach.',
    price: 85,
    img: '/src/assets/modric.webp',
    legendary: false,
    position: 'Midfielder',
    attributes: {
      dribbling: 90,
      speed: 79,
      shot: 86,
      defensive: 79,
      overall: 88,
    },
  },
  {
    id: 11,
    name: 'Jan Oblak',
    description: 'Bramkarz, o niezwykłych refleksach i umiejętnościach interwencji.',
    price: 100,
    img: '/src/assets/oblak.webp',
    legendary: false,
    position: 'Goalkeeper',
    attributes: {
      dribbling: 30,
      speed: 55,
      shot: 40,
      defensive: 96,
      overall: 91,
    },
  },
  {
    id: 12,
    name: 'Kevin De Bruyne',
    description: 'Pomocnik, znany z precyzyjnych podań i zdolności do strzelania z dystansu.',
    price: 110,
    img: '/src/assets/bruyne.webp',
    legendary: false,
    position: 'Midfielder',
    attributes: {
      dribbling: 91,
      speed: 81,
      shot: 89,
      defensive: 72,
      overall: 90,
    },
  },
])
